---
- hosts: 172.31.91.242
  become: yes
  gather_facts: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: I want to create a directory
    file:
      path: /home/venkat/myfolder
      state: directory

  - name: I want to copy a file
    copy:
      src: mytextfile
      dest: /home/venkat/myfolder/mytextfile
  - name: Install apache2
    apt:
      name: apache2
      state: present   
  - name: I want to copy index.html file into node
    template:
         src: myindex.j2
         dest: /var/www/html/index.html  

  - name: I want to download remote file 
    get_url:
        url: https://github.com/maha4dsvc/myAnsible_DS_E_7PM_26Nov24/blob/main/myStudents.yml
        dest: /home/venkat
        force_basic_auth: yes       