---
- hosts: all
  become: yes
  tasks: 
  - name: install apache2 webserver
  apt:
    name: apache2
    state: present  
- name: I want to install wwebserver 
  service:
    name: apache2
    state: restarted

    

