---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: install apache2 webserver
    apt:
      name: "{{mywebpackage}}"
      state: present
    when: ansible_os_family=="Debian"   
  - name: I want to install wwebserver 
    service:
      name: "{{mywebpackage}}"
      state: restarted
    when: ansible_os_family=="Debian"    

    

