---
 - name: I want to download tomcat gz file.
   get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.33/bin/apache-tomcat-10.1.33.tar.gz
       dest: /home/venkat/apache-tomcat-10.1.33.tar.gz
       force_basic_auth: yes 

 - name: create a tomcat directory 
   file:
     path: /opt/tomcat
     state: directory

 - name: Extract tomcat directory
   unarchive:
     src: /home/venkat/apache-tomcat-10.1.33.tar.gz
     dest: /opt/tomcat
     remote_src: yes 